# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Publications
    url: '/publication/'
    weight: 40
  - name: Open Science
    url: '/openScience/'
    weight: 50
  - name: Posts
    url: '/post/'
    weight: 60
  - name: Resume/CV
    url: 'files/cv.pdf'
    weight: 70

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
