# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: my_theme
  theme_night: my_theme
  font: custom_font
  font_size: M

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Nick Ballou, games psychology and meta-science researcher.'
    twitter: 'nbballou'
  analytics:
    google_analytics: 'G-RJ9TB95D0V'
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: false
    highlight_active_link: true

# Site footer

footer:
  copyright:
    notice: 'Â© {year} Nick Ballou. This work is licensed under {license}.'
    license:
      enable: true
      allow_derivatives: true
      share_alike: true
      allow_commercial: true

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    theme_light: igor
    theme_dark: nord
    enable: true
    extra_languages:
      - r
      - latex
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/nballou/nickballousite'
    content_dir: content
    branch: master
  avatar:
    gravatar: false
    shape: square
  comment:
    provider: 'giscus'
    commentable: {page = true, post = true, blog = true, docs = false, project = false, publication = true, talk = false}
    giscus:
      repo: 'nballou/giscus'
      repo_id: 'R_kgDOInYdlg'
      category: 'Announcements'
      category_id: 'DIC_kwDOInYdls4CTEjO'
      label: 'comment'
      theme: preferred_color_scheme
      reactions_enabled: 0
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Security

security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: true

plugins_css: ["custom","codefolding"]

############################
## Code folding
############################

# Set to true to disable code folding
disable_codefolding: false
# Set to show to show all by default, hide to hide all by default - don't put inside quotes
codefolding_show: show
# Set to true to exclude the "Show/hide all" button
codefolding_nobutton: false

############################
## Books
############################

docs_section_pager: true